services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    command: >
      /bin/sh -c
      'python manage.py runserver 0.0.0.0:8000'

  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
